// react_auth_basic/app/components/Head.tsx
import React from "react";
import {Link } from 'react-router-dom';
//
function Page() {
    return (
    <div>
        <Link to="/">Home</Link>
        <Link to="/about" className="mx-2" > [ about ]</Link>
        <Link to="/login" className="mx-2" > [ login ]</Link>
        <hr />
    </div>
    );
}
export default Page;

// svelte_auth_drizzle/app/components/Head.svelte
<script>
	import {link} from 'svelte-spa-router'
</script>

<header class="">
  <div class="container">
    <span><a href="/" use:link>[ Home ]</a>
    </span>
    <span><a href="/login" use:link>[ login ]</a>
    </span>
    <span><a href="/todo" use:link>[ todo ]</a>
    </span>
  </div>
  <hr />
</header>
<!--
<span><a href="/about" use:link>[ about ]</a>
</span>
-->
