// svelte_task/app/components/Head.svelte
<script>
	import {link} from 'svelte-spa-router'
</script>

<header class="">
  <div class="container">
    <span><a href="/" use:link>[ Home ]</a>
    </span>
    <span><a href="/about" use:link>[ about ]</a>
    </span>
    <span><a href="/task_project" use:link>[ TaskProject ]</a>
    </span>
    <span><a href="/todo" use:link>[ todo ]</a>
    </span>
  </div>
  <hr />
</header>

// react_app/app/components/Head.tsx
//import { Routes, Route, Link } from 'react-router-dom';
import React from "react";
import {Link } from 'react-router-dom';
//
function Page() {
    return (
    <div>
        <Link to="/">Home</Link>
        <Link to="/about" className="mx-2" > [ about ]</Link>
        <Link to="/todo" className="mx-2" > [ todo ]</Link>
        <Link to="/todo11" className="mx-2" > [ todo11 ]</Link>
        <hr />
    </div>
    );
}
export default Page;
